def assemble(*args):
    return " ".join(args)


def NP(T, N):
    return assemble(T,N)

def VerbVerb(Verb, Verba):
    return assemble(Verb, Verba)






def loop(X):

    T = ['I do not mean anyone else but you',
         'Oh babe, you know how it looks like',
         'Some people are just nasty as hell',
         'it is extremely rare',
         'I feel stressed out recently',
         'My head is banging and I feel bit drowzy',
         'You ar such an interesting guy ',
         'Love needs to be taken seriously',
         'You have a such an interesting personality',
         'If wew ever went out for a food, I hate anything mild',
         'How would you describe yourself?',
         'I love bacon, beer, birds',
         'No , I am not crazy at all',
         'Life would be terrible without a good conversation',
         'I cannot tell you that',
         'Listen, do not be angry at me',
         'I have not slept very well today',
         'Oh, I wish that too babe',
         'I cannot do it babe',
         'Oh you are so funny seriously',
         'I have never been there',
         'Im a great listener, really good with empathy',
         'I believe that you have enjoyed your meal',
         'I am really into that kind of stuff but',
         'Choosing to do nothing is still a choice, after all',
         'I found your complete dullness interesting',
         'I really do not know what to think about it',
         'Oh my god, You are so cute ',
         'I do freaking wish that',
         'I really do not know how',
         'I would like to know how',
         'Love never comes easy',
         'You are so much romantic !',
         'I am so happy that you like my looks anyway',
         'I do like when you find my face, my body aesthetic',
         'My friends keep telling me',
         'I gotta stop talking about food',
         'Italian food is overrated I suppose',
         'I am not picky with anything',
         'Do not tell me I am a bad guy here',
         'I cannot do it yet sorry',
         'Oh gosh I forgot how much busy I am this week',
         'I cannot find anything to watch recently',
         'I know how you feel babe',
         'I do not want you to be me mad at me',
         'I knew you are going to like it',
         'I work remotely nowadays',
         'it is always better to think clearly',
         'I should be more hardworking',
         'Some company would help me a lot',
         'Could imagine not talking at all?',
         'You have got me blushing out Darling',
         'I know you might not chat always, but',
         'what are you doing right now?']
    N = ['I have been sick a bit',
         'Can you tell me what is going on',
         'I hope you know what was wrong',
         'I am taping my nails at the moment',
         'It will not be so easy',
         'You have a good sense of humor',
         'I do not try anything new',
         'I try to take convos serious trust me',
         'I need to eat something did you eat well?',
         'time is so much important',
         'I do not use anything apart from here',
         'I am a crazy girl',
         'I act insane sometimes',
         'I hope you enjoyed your day',
         'I do not see the phone number',
         'I feel more secure here',
         'maybe watch a movie or something',
         'I will cook some good ass food for sure',
         'I usually don’t talk about that kind of stuff',
         'it is a lot more enjoyable',
         'do not even try to convince me to anything different',
         'I have been played by many guys',
         'my heart has been broken so many times',
         'computer needs to be replaced',
         'my phone is trash so bad',
         'my family annoys me',
         'I am telling you that',
         'I do really like it tho',
         'I cannot meet now babe',
         'I am getting wet as hell',
         'I am not gonna lie',
         'if you ever would like to kiss me do not eat garlic before',
         'I am so achy today I dunno',
         'I have too much work recently',
         'that is so fantastic',
         'it makes me wanna cum',
         'It is still nice I think',
         'it is extremely sexy',
         'it is definitely great!',
         'it excites me a lot really',
         'it is definitely a game changer',
         'so crazy out here for real',
         'it is too bad for real',
         'I am here to listen to you',
         'I wish could be less lazy',
         'Tell me about something unusual',
         'What do you do for work?',
         'Do you ever get frustrated about some people?',
         'Do you think life is hard?',
         'What do you think about it ?',
         'What is your opinion on that ?',
         'Have you ever had a dream that came true ?',
         'Do you have any cool series?',
         'Is there any fantasies to make them come true?',
         'A hard cock is the only thing I am asking for',
         'I do not give the address to soon',
         'Some people are sneaky as hell',
         'I cannot stand the pandemic anymore',
         'I will miss you, baby, if youll ever leave me',
         'Oh you mean we should stop talking here',
         'Hmmm other side like what baby',
         'Dont you have me now?',
         'I have been pretty good',
         'Trust that you have been very well',
         'I really wish it wasnt going to end like this',
         'It sounds like you have been enjoying yourself',
         'Do you have another woman?',
         'Are you watching the TV all alone '
         ]
    Verb = ['I would really like to',
            'Oh no, I cannot let myself',
            'I just realized that I',
            'I do not want to be lonely anymore and',
            'I wish that someone could come and',
            'I want to be with you and',
            'Jesus Christ, I',
            'I wish that everything about me could',
            'I feel that many people want to',
            'I just want to',
            'I really wanted to',
            'I heard that the girl',
            'I am about to',
            'I need to relax I',
            'Will we ever',
            'I am too shy need to',
            'I really should do',
            'I wish we could ',
            'I feel that some girls wanna',
            'I think that some guys wanna',
            'I am sorry but I',
            'I am happy that I',
            'I do not not know if I',
            'I am not really sure whether I',
            ]
    Verba = ['find someone who is not toxic',
             'have finally some sex',
             'have good time with you',
             'be more confident',
             'enjoy life as a normal person',
             'be finally independent',
             'find the meaning of life',
             'change it.',
             'watch some decent tv shows',
             'be very tired',
             'be kinky sometimes',
             'try something unusual',
             'finally meet',
             'try the other hole',
             'get naughty together',
             'be very turned on',
             'let you cuddle me so hard',
             'cause affection',
             'get some decent sleep',
             'try some not boring sex',
             'be fair and real',
             'be more serious towards people',
             'be finally smarter',
             'give up drinking',
             'have the decision to make',
             'be less confused',
             'carry on with good life',
             'think that it will work out',
             'actually bring that much happiness to you']


    import random as ran

    for i in range(X):

        N1 = ran.choice(N)
        T1 = ran.choice(T)
        Verb1 = ran.choice(Verb)
        Verb2 = ran.choice(Verba)
        NP1 = NP(T1,N1)
        VerbVerb1 = VerbVerb(Verb1,Verb2)

        print("  - ",NP1,".",VerbVerb1)

loop(10000)